language: 
  - node_js
  - android
node_js:
  - "node"
android:
  components:
    - build-tools-27
    - android-26
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - yarn i -g cordova
install:
  npm install
script:
  - cd ./angularFiles && yarn i
  - ng test
  - cd ../mobileApp && cordova prepare && npm run build
branches:
  only:
  - TravisIntigration