sudo: false

language: node_js
node_js:
  - "lts/*"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g gulp cordova
  - npm install
  # - bower update

before_script:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - unzip sdk-tools-linux-4333796.zip
  - echo y | ./tools/bin/sdkmanager packages platform-tools
  - echo y | ./tools/bin/sdkmanager packages build-tools-27.0.2
  - echo y | ./tools/bin/sdkmanager packages android-27
  - echo y | ./tools/bin/sdkmanager packages extra-android-support
  - echo y | ./tools/bin/sdkmanager packages extra-android-m2repository
  - echo y | ./tools/bin/sdkmanager packages extra-google-m2repository        
  - ls
  - export ANDROID_HOME=$PWD/tools
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  - cordova prepare
branches:
  only:
  - TravisIntigration