sudo: required
language: 
  android
  # node_js
jdk: oraclejdk8
node_js: 
  - "10"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27

dist: trusty
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  # - sudo chown root /usr/lib/node_modules
  # - sudo chmod 777 /usr/lib/node_modules
addons:
    - chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  # npm: true
  directories:
    # - $HOME/.yarn-cache
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/
install:
  # npm install
  - sudo npm i -g cordova
script:
  - ls ~/builds/
  - echo  ----------------------- 
  - echo $ANDROID_HOME
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration









