language: 
  - node_js
  - android
node_js:
  - "lts/*"
android:
  components:
    - build-tools-26
    - android-26
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  # npm: true
  directories:
    # - $HOME/.yarn-cache
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/
install:
  # npm install
  - npm i -g cordova
script:
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration