os:
  linux
sudo: required
language: 
  android
jdk: oraclejdk8
node_js: 
  - "10"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27
    - extra-google-m2repository
    - addons

dist: trusty
addons:
    apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - yes | sdkmanager "platforms;android-27"
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - sudo apt-get install nodejs
    - sudo apt-get install build-essential
    - PATH=$PATH:$JAVA_HOME/bin
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  # npm: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/

install:
  - sudo npm i -g npm
  - sudo npm i -g @angular/cli
  - sudo npm i -g cordova
  - export ANDROID_HOME=/usr/local/android-sdk/
script:
  - ./gradlew test
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration









