sudo: required
language: 
  android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27

dist: trusty
env:
  - NVM_DIR='$HOME/.nvm'
before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  # - export NVM_DIR='$HOME/.nvm'
  - $NVM_DIR/nvm.sh
   # This loads nvm
  - nvm install --lts
addons:
    - chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  # npm: true
  directories:
    # - $HOME/.yarn-cache
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/
install:
  # npm install
  - npm i -g cordova
script:
  - ls ~/builds/
  - echo  ----------------------- 
  - echo $ANDROID_HOME
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration