language: 
  - node_js
  - android
sudo: required
jdk: oraclejdk8
node_js:
  - "lts/*"
android:
  components:
     - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra
jdk:
    - oraclejdk8
dist: trusty
addons:
    - chrome: stable
    - apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
        - openjdk-7-jdk
        - lib32stdc++6
        - lib32z1
env:
  CXX=g++-4.8
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    # - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    # - tar -xvf sdk-tools-linux-4333796.zip
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-27.0.1
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-26
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
    # - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
    # - export ANDROID_HOME=$PWD/android-sdk-linux
    # - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
cache:
  # npm: true
  directories:
    # - $HOME/.yarn-cache
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/
install:
  # npm install
  - npm i -g cordova
script:
  - ls ~/build/
  - ls ~/build/Keith3895/
  - ls ~/build/Keith3895/financeTracker/
  - echo -----------------------
  - 
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration









