language: 
  - node_js
  - android
node_js:
  - "node"
android:
  components:
    - build-tools-27
    - android-26
cache:
  yarn: true
  directories:
    - node_modules
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - yarn i -g cordova
install:
  npm install
script:
  - cd ./angularFiles && yarn i
  - ng test
  - cd ../mobileApp && cordova prepare && npm run build
branches:
  only:
  - TravisIntigration