language: 
  - node_js
  - android
node_js:
  - "lts/*"
android:
  components:
    - build-tools-27
    - android-26
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
install:
  # npm install
  - npm i -g cordova
script:
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && cordova prepare && npm run build
branches:
  only:
  - TravisIntigration