sudo: required
language: 
  android
  node_js
jdk: oraclejdk8
node_js: 
  - "10"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - addons

dist: trusty
addons:
    apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - sudo apt-get install nodejs
    - sudo apt-get install build-essential
    - PATH=$PATH:$JAVA_HOME/bin
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  # npm: true
  directories:
    - node_modules
    - /home/travis/build/Keith3895/financeTracker/angularFiles/node_modules/
script:
  - ls ~/builds/
  - echo  ----------------------- 
  - echo $ANDROID_HOME
  - sudo npm i -g cordova
  - cd ./angularFiles && npm i
  - ng test
  - cd ../mobileApp && npm run build
branches:
  only:
  - TravisIntigration









